### PR TITLE
Update action struct for updateCheckItemStateOnCard Action type

### PR DESCRIPTION
**Pull request by lmsilvera**

### CODE REVIEW

**Comment by VojtechVitek** [comment]
@lmsilvera thanks for your contribution! Can you use gofmt to format your code changes? https://blog.golang.org/go-fmt-your-code

**Comment by lmsilvera** [comment]
Great, I do it.

**Comment by lmsilvera** [comment]
The code it's ready :+1:

**Comment by lmsilvera** [comment]
And is needed refresh the documentation.

**Comment by VojtechVitek** [comment]
LGTM. The godoc will be updated automatically. Thanks again!

**Pull request merged**
