### PR TITLE
Authentication through trello token, some API fixes and POST for webhooks

### PR DESCRIPTION
**Pull request by jeromenerf**
Hey @VojtechVitek 

as we discussed a bit earlier this year, here is a WIP including auth and POST for webhook.

I also refactored some parts to reduce verbosity.

Go 1.5 is required to get `Offset` on json.Marshal errors (https://github.com/VojtechVitek/go-trello/compare/master...jeromenerf:master#diff-458673b146dc31d51dd3af03121d00d6R103).

We should take some time to implement POST / DELETE on cards, lists, etc. This is pretty straight forward.

See https://github.com/VojtechVitek/go-trello/issues/1

### CODE REVIEW

**Comment by VojtechVitek** [comment]
Looks good so far! Is this still WIP or can I merge this?

Thanks!

**Comment by VojtechVitek** [comment]
@jeromenerf can I merge this, is it ready?

**Comment by jeromenerf** [comment]
Morning!

This is still WIP, since all methods are not yet implemented on all resources and test coverage is pretty low. Maybe merge in a feature / staging branch?

**Comment by VojtechVitek** [comment]
@jeromenerf let's leave it as Pull Request, until we have all methods :) Thanks!

**Comment by VojtechVitek** [comment]
Closing in favor of #6, which was influenced by this PR. The commits reference you @jeromenerf, so thanks again for your great work and contributions!

**Comment by eparis** [comment]
This PR has 3 pieces mine doesn't have.

`Attachment`, `Comment`, and any kind of webhooks.

a PR to bring the first 2 in would be REALLY easy. I'll do that right now.  But I'm not playing with the webhooks, so I'm not going to take that plunge....

**Pull request closed without merging**
